### ISSUE TITLE
The project is dead or are you available to accept contributes?

### ISSUE THREAD

**Issue by AlessandroMIlani** [munabedan/incul-manager#1]
Hi, I've started to work on some improvement in my fork and i want to know if you still interested in a pull request, because i see that are no commit in the last 5 months and from the read me i don't understand if you are still working on it or no.

PS. At the end of the read me in my fork you can find a TODO list regarding what points I want to implement/improve

**Comment by munabedan** [comment]
Dude awesome, great to see someone caught interest in the idea. I am available to accept contributions.

**Comment by AlessandroMIlani** [comment]
Ho, nice.
So, at the moment, I've finished applying two main modification:
- have a different username and password for each template and container
- be sure that each container have its private network (in your version, with same subnet and same user/password, it's possible to move file from different containers with an scp command or create ssh connections, and I prefer to avoid it for security)

If you agree, as soon as I have time, I clean up my current main branch and open a pull request with only these 2 changes

**Comment by munabedan** [comment]
Yeah, I have preemptively taken a look at your commit history. I like the improvements you have implemented. Do send them to me when you are ready, so I can take a look.

Might I ask, how did you find out about the project?

**Comment by AlessandroMIlani** [comment]
An Italian YouTuber found your post on Reddit while it was looking for container-based alternatives to QubesOS. 
[incul manager, l'alternativa leggera a Qubes OS](https://www.youtube.com/watch?v=82eVPgPxawc)

**Comment by munabedan** [comment]
I was really wondering why I am getting so many follows all of a sudden from GitHub users with Italian names. Looking forward to working on this project again.
